### PR TITLE
Fixed the missing debugInformation

### PR DESCRIPTION
**Pull request by jmartschinke**

### CODE REVIEW

**Comment by Ralf1108** [comment]
Looks very good. Didn't know that the fix was so small. Thank you very much for your contribution! @

**Comment by Ralf1108** [comment]
Looks very good. Didn't know that the fix was so small. Thank you very much for your contribution!

**Comment by jmartschinke** [comment]
> Looks very good. Didn't know that the fix was so small. Thank you very much for your contribution! @

Was actually my first contribution ever! Thanks for the quick reply! When will a new NuGet package be published?

**Comment by Martinay** [comment]
it seems that there is an issue with our build pipeline. I'll have a look into that in the next days (hopefully latest on the weekend)

**Comment by jmartschinke** [comment]
No problem!
I'm looking forward to the release :)

**Comment by Martinay** [comment]
the new nuget package is published  -> version 2.0.139

**Pull request merged**
