### PR TITLE
Revert "Fix debug information by just using the debug scopes from ori…

### LINKED ISSUE #101: Unable to set debug breakpoint in methods with sequence points
## Problem
Setting a break point in Visual Studio or VS Code within a decorated method with sequence points results in the breakpoint being ignored.

## Expected Result
The debugger should be able to find the breakpoint and break.

## Minimum reproducible code
```pwsh
mkdir \temp\mba-test
cd \temp\mba-test
dotnet new console
dotnet add package Fody
dotnet add package MethodBoundaryAspect.Fody
code .
```

Program.cs
```csharp
using MethodBoundaryAspect.Fody.Attributes;

public static class Program
{
    private static void Main()
        => new Interactor().DoSomething();
}

public class Interactor
{
    [DummyAspect]
    public void DoSomething()
    {
        if (true)
        {
            Console.WriteLine("Hello world");
        }
    }
}

public class DummyAspect : OnMethodBoundaryAspect
{
    public override void OnEntry(MethodExecutionArgs arg)
        => base.OnEntry(arg);
}

```

From Visual Studio or VS Code, set a breakpoint within Interactor.DoSomething() (Lines 13-18). Run the program from IDE. The breakpoint is never hit.

This appears to be a regression with v2.0.146. Setting the MethodBoundaryAspect.Fody version to 2.0.145 produces the expected result.

### PR DESCRIPTION
**Pull request by psaxton**
Revert "Fix debug information by just using the debug scopes from original method".

Fixes #101 

This reverts commit 9d451fbff2290110dc53d0a82caacb744fe782f4.

### CODE REVIEW

**Comment by Ralf1108** [comment]
Currently at HEAD is the merge of [1cb1c708c0b19be7dd3452e0a1644f27f1ebf895](commit:1cb1c708c0b19be7dd3452e0a1644f27f1ebf895) which was released as v2.0.147-pre.
Should we keep this before merging your PR?

**Comment by psaxton** [comment]
I think it's up to you how you want it versioned. If you want to include it
under .147 I'll rebase. If you want to keep it as .146.1 or something I'll
update the #66 fix PR.

**Comment by Ralf1108** [comment]
Ok, then keep the changes in v2.0.147-pre as there weren't any new issues

**Comment by psaxton** [comment]
Rebased to current master.

**Pull request merged**
